openapi: 3.0.0
info:
  title: Xero Bank Feeds API
  description: The Bank Feeds API is a closed API that is only available to financial institutions that
    have an established financial services partnership with Xero. If you're an existing financial services
    partner that wants access, contact your local Partner Manager. If you're a financial institution who
    wants to provide bank feeds to your business customers, contact us to become a financial services
    partner.
  termsOfService: https://developer.xero.com/xero-developer-platform-terms-conditions/
  contact:
    name: Xero Platform Team
    url: https://developer.xero.com
    email: api@xero.com
  license:
    name: MIT
    url: https://github.com/XeroAPI/Xero-OpenAPI/blob/master/LICENSE
  version: 19.0.0
servers:
- url: https://api.xero.com/bankfeeds.xro/1.0
  description: Xero Bank Feeds API base url
paths:
  /FeedConnections:
    get:
      tags:
      - BankFeeds
      summary: Searches for feed connections
      description: By passing in the appropriate options, you can search for available feed connections
        in the system.
      operationId: getFeedConnections
      parameters:
      - name: page
        in: query
        description: Page number which specifies the set of records to retrieve. By default the number
          of the records per set is 10. Example - https://api.xero.com/bankfeeds.xro/1.0/FeedConnections?page=2
          to get the second set of the records. When page value is not a number or a negative number,
          by default, the first set of records is returned
        required: false
        style: form
        explode: true
        schema:
          type: integer
          example: 1
      - name: pageSize
        in: query
        description: Page size which specifies how many records per page will be returned (default 10).
          Example - https://api.xero.com/bankfeeds.xro/1.0/FeedConnections?pageSize=100 to specify page
          size of 100
        required: false
        style: form
        explode: true
        schema:
          type: integer
          example: 100
      responses:
        '202':
          description: A page of feed connections, with pagination details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FeedConnections'
              example:
                pagination:
                  page: 1
                  pageCount: 1
                  pageSize: 87654321
                  itemCount: 39
                items:
                - id: c0eb97b5-4f97-465a-8268-276513c14396
                  accountToken: foobar31306
                  accountType: BANK
                  accountNumber: '123496842'
                  accountName: SDK Bank 95921
                  accountId: aefbf6be-4285-4ca5-bf39-0f486c8515c7
                  currency: GBP
                  country: GB
                - id: 3b44b539-4e39-4d53-9334-d8ba01674752
                  accountToken: foobar74770
                  accountType: BANK
                  accountNumber: '123481122'
                  accountName: SDK Bank 11272
                  accountId: fc2f3cc2-126e-40d7-9fc1-12e52d0a71f1
                  currency: GBP
                  country: GB
        '400':
          description: validation error response
      security:
      - OAuth2:
        - bankfeeds
    post:
      tags:
      - BankFeeds
      summary: Creates one or more new feed connections
      description: By passing in the FeedConnections array object in the body, you can create one or more
        new feed connections
      operationId: createFeedConnections
      parameters:
      - $ref: '#/components/parameters/idempotencyKey'
      requestBody:
        description: Feed Connection(s) array object in the body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FeedConnections'
            example:
              items:
              - accountToken: foobar71760
                accountNumber: '123458637'
                accountName: SDK Bank 90861
                accountType: BANK
                currency: GBP
        required: true
      responses:
        '202':
          description: The submitted feed connections, each with its status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FeedConnections'
              example:
                items:
                - id: 2a19d46c-2a92-4e50-9401-dcf2cb895be7
                  accountToken: foobar71760
                  status: PENDING
        '400':
          description: failed to create new feed connection(s)response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FeedConnections'
              example:
                items:
                - accountToken: foobar71760
                  status: REJECTED
                  error:
                    type: invalid-request
                    title: Invalid Request
                    status: 400
                    detail: For the request field 'AccountNumber' exceeded the maximum length of 40.
      security:
      - OAuth2:
        - bankfeeds
      x-hasBankFeedsValidationError: true
    parameters:
    - $ref: '#/components/parameters/requiredHeader'
  /FeedConnections/{id}:
    get:
      tags:
      - BankFeeds
      summary: Retrieves a single feed connection by its unique ID
      description: By passing in a FeedConnection Id options, you can search for matching feed connections
      operationId: getFeedConnection
      parameters:
      - name: id
        in: path
        description: Unique identifier for retrieving single object
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: uuid
      responses:
        '200':
          description: The feed connection matching the given ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FeedConnection'
              example:
                id: b58b685a-1bee-4904-91f1-fee30bb6ea52
                accountToken: foobar84778
                accountType: BANK
                accountNumber: '123434859'
                accountName: SDK Bank 5517
                accountId: f4c4d595-da94-493b-999a-19d1ae1f508a
                currency: GBP
                country: GB
        '400':
          description: bad input parameter
      security:
      - OAuth2:
        - bankfeeds
    parameters:
    - $ref: '#/components/parameters/requiredHeader'
  /FeedConnections/DeleteRequests:
    post:
      tags:
      - BankFeeds
      summary: Deletes one or more existing feed connections
      description: By passing in FeedConnections array object in the body, you can delete a feed connection.
      operationId: deleteFeedConnections
      parameters:
      - $ref: '#/components/parameters/idempotencyKey'
      requestBody:
        description: Feed Connections array object in the body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FeedConnections'
            example:
              items:
              - id: b4cc693b-24d9-42ec-a6d4-2943d253ff63
        required: true
      responses:
        '202':
          description: The feed connections submitted for deletion, each with its status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FeedConnections'
              example:
                items:
                - id: b4cc693b-24d9-42ec-a6d4-2943d253ff63
                  status: PENDING
                - accountToken: '10000125'
                  status: REJECTED
                  error:
                    type: feed-connected-in-different-organisation
                    title: Feed connected in different organisation
                    detail: The AccountToken is connected to another Xero Bank Account associated with
                      this bank. This Xero Bank Account belongs to a different Xero Organisation.
        '400':
          description: bad input parameter
      security:
      - OAuth2:
        - bankfeeds
    parameters:
    - $ref: '#/components/parameters/requiredHeader'
  /Statements:
    get:
      tags:
      - BankFeeds
      summary: Retrieves all statements
      description: By passing in parameters, you can search for matching statements
      operationId: getStatements
      parameters:
      - name: page
        in: query
        description: Page number which specifies the set of records to retrieve. By default the number
          of the records per set is 10. Example - https://api.xero.com/bankfeeds.xro/1.0/Statements?page=2
          to get the second set of the records. When page value is not a number or a negative number,
          by default, the first set of records is returned
        required: false
        style: form
        explode: true
        schema:
          type: integer
          format: int32
      - name: pageSize
        in: query
        description: Page size which specifies how many records per page will be returned (default 10).
          Example - https://api.xero.com/bankfeeds.xro/1.0/Statements?pageSize=100 to specify page size
          of 100
        required: false
        style: form
        explode: true
        schema:
          type: integer
          format: int32
      - name: Xero-Application-Id
        in: header
        description: Xero identifier of the application making the request
        required: false
        style: simple
        explode: false
        schema:
          type: string
          default: 00000000-0000-0000-0000-0000000010000
        x-ballerina-name: xeroApplicationId
      - name: Xero-User-Id
        in: header
        description: Xero identifier of the user on whose behalf the request is made
        required: false
        style: simple
        explode: false
        schema:
          type: string
          default: 00000000-0000-0000-0000-0000030000000
        x-ballerina-name: xeroUserId
      responses:
        '200':
          description: A page of statements, with pagination details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Statements'
              example:
                pagination:
                  page: 1
                  pageCount: 210
                  pageSize: 3
                  itemCount: 3
                items:
                - id: 9817e4b8-82b3-4526-91f7-040bd278053f
                  feedConnectionId: 6a4b9ff5-3a5f-4321-936b-4796163550f6
                  status: REJECTED
                  startDate: '2019-08-01'
                  endDate: '2019-08-15'
                  startBalance:
                    amount: 100.0000
                    creditDebitIndicator: CREDIT
                  endBalance:
                    amount: 150.0000
                    creditDebitIndicator: CREDIT
                  statementLineCount: 1
                  errors:
                  - type: duplicate-statement
                    title: Duplicate Statement Received
                    status: 409
                    detail: The received statement was marked as a duplicate.
                - id: 2fc57bac-7aa7-4981-a5cd-8aee83fe698c
                  feedConnectionId: 6a4b9ff5-3a5f-4321-936b-4796163550f6
                  status: DELIVERED
                  startDate: '2019-08-01'
                  endDate: '2019-08-15'
                  startBalance:
                    amount: 100.0000
                    creditDebitIndicator: CREDIT
                  endBalance:
                    amount: 150.0000
                    creditDebitIndicator: CREDIT
                  statementLineCount: 1
        '400':
          description: bad input parameter
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Statements'
              example:
                type: invalid-request
                title: Invalid Request
                status: 400
                detail: For the request field missing parameter.
      security:
      - OAuth2:
        - bankfeeds
    post:
      tags:
      - BankFeeds
      summary: Creates one or more new statements
      operationId: createStatements
      parameters:
      - $ref: '#/components/parameters/idempotencyKey'
      requestBody:
        description: Statements array of objects in the body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Statements'
            example:
              items:
              - feedConnectionId: 6a4b9ff5-3a5f-4321-936b-4796163550f6
                startDate: '2019-08-11'
                endDate: '2019-08-11'
                startBalance:
                  amount: '100'
                  creditDebitIndicator: CREDIT
                endBalance:
                  amount: '150'
                  creditDebitIndicator: CREDIT
                statementLines:
                - postedDate: '2019-08-11'
                  description: My new line
                  amount: '50'
                  creditDebitIndicator: CREDIT
                  transactionId: '123446422'
                  payeeName: StarLord90315
                  reference: Foobar95578
                  chequeNumber: '12379009'
                  transactionType: Refund
              - feedConnectionId: 2ebe6393-f3bb-48ab-9a0e-b04fa8585a70
                startDate: '2019-08-11'
                endDate: '2019-08-11'
                startBalance:
                  amount: '100'
                  creditDebitIndicator: CREDIT
                endBalance:
                  amount: '150'
                  creditDebitIndicator: CREDIT
                statementLines:
                - postedDate: '2019-08-11'
                  description: My new line
                  amount: '50'
                  creditDebitIndicator: CREDIT
                  transactionId: '123449402'
                  payeeName: StarLord56705
                  reference: Foobar67355
                  chequeNumber: '12379350'
                  transactionType: Currency Conversion Fee
        required: true
      responses:
        '202':
          description: The submitted statements, each with its status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Statements'
              example:
                items:
                - id: d69b02b7-a30c-464a-99cf-ba9770373c61
                  feedConnectionId: 6a4b9ff5-3a5f-4321-936b-4796163550f6
                  status: PENDING
                - id: 598f255c-015b-4138-93df-2e06c64565b3
                  feedConnectionId: 2ebe6393-f3bb-48ab-9a0e-b04fa8585a70
                  status: PENDING
        '400':
          description: Statement failed validation
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Statements'
              example:
                type: invalid-request
                title: Invalid Request
                status: 400
                detail: For the request field 'StatementLine.ChequeNumber' exceeded the maximum length
                  of 20.
        '403':
          description: Invalid application or feed connection
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                type: invalid-application
                title: Invalid Application
                status: 403
                detail: The application has not been configured to use these API endpoints.
        '409':
          description: Duplicate statement received
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Statements'
              example:
                items:
                - id: 29fefeb6-f449-470d-9179-f1d8900930d6
                  feedConnectionId: 6a4b9ff5-3a5f-4321-936b-4796163550f6
                  status: REJECTED
                  errors:
                  - type: duplicate-statement
                    title: Duplicate Statement Received
                    status: 409
                    detail: The received statement was marked as a duplicate.
        '413':
          description: Statement exceeds size limit
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Statements'
              example:
                type: invalid-request
                title: Request too large
                status: 413
                detail: Request size of 3500000 bytes exceeds the limit of 3000000 bytes.
        '422':
          description: Unprocessable Entity
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Statements'
              example:
                type: invalid-end-balance
                title: Invalid End Balance
                status: 422
                detail: End balance does not match start balance +/- statement line amounts.
        '500':
          description: Intermittent Xero Error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Statements'
              example:
                type: internal-error
                title: Intermittent Internal Xero Error
                status: 500
                detail: The request should be retried. If the error persists, a Xero support issue should
                  be raised.
      security:
      - OAuth2:
        - bankfeeds
      x-hasBankFeedsValidationError: true
    parameters:
    - $ref: '#/components/parameters/requiredHeader'
  /Statements/{statementId}:
    get:
      tags:
      - BankFeeds
      summary: Retrieves a single statement by its unique ID
      description: By passing in a statement id, you can search for matching statements
      operationId: getStatement
      parameters:
      - name: statementId
        in: path
        description: statement id for single object
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: uuid
      responses:
        '200':
          description: The statement matching the given ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Statement'
              example:
                id: 97aca24a-dd10-4cda-98c7-1084a048257b
                feedConnectionId: 6a4b9ff5-3a5f-4321-936b-4796163550f6
                status: DELIVERED
                startDate: '2019-08-11'
                endDate: '2019-10-11'
                startBalance:
                  amount: 100.0000
                  creditDebitIndicator: CREDIT
                endBalance:
                  amount: 150.0000
                  creditDebitIndicator: CREDIT
                statementLineCount: 1
        '404':
          description: Statement not found
      security:
      - OAuth2:
        - bankfeeds
    parameters:
    - $ref: '#/components/parameters/requiredHeader'
components:
  schemas:
    FeedConnection:
      type: object
      properties:
        accountId:
          type: string
          description: Xero identifier for a bank account in Xero. Must be included if AccountNumber is
            not specified
          format: uuid
          example: 079a88ea-276d-41fb-a1f1-366ef3e22921
        country:
          description: Country of the bank account, as an ISO-3166 alpha-2 country code
          allOf:
          - $ref: '#/components/schemas/CountryCode'
        accountName:
          maximum: 30
          type: string
          description: The Account Name will be used for the creation of a new Xero Bank Account if a
            matching Xero Bank Account is not found
          example: Joe's Savings Account
        accountType:
          type: string
          description: High level bank account type - BANK CREDITCARD BANK encompasses all bank account
            types other than credit cards
          example: BANK
          enum:
          - BANK
          - CREDITCARD
        currency:
          description: Currency of the bank account, as an ISO-4217 currency code
          allOf:
          - $ref: '#/components/schemas/CurrencyCode'
        id:
          type: string
          description: GUID used to identify the Account
          format: uuid
          example: 00d3cf8d-95dc-4466-8dc0-47e6d1197e28
        accountToken:
          maximum: 50
          type: string
          description: This account identifier is generated by the financial institute (FI). This must
            be unique for your financial institute
          example: '10000123'
        accountNumber:
          maximum: 40
          type: string
          description: String(40) when AccountType is BANK String(4) when AccountType is CREDITCARD The
            Account Number is used to match the feed to a Xero Bank Account. The API will create a new
            Xero Bank Account if a match to an existing Xero Bank Account is not found. Only the last
            4 digits must be supplied for Credit Card numbers. Must be included if AccountId is not specified
          example: '3809087654321500'
        error:
          description: Details of why the feed connection request was rejected
          allOf:
          - $ref: '#/components/schemas/Error'
        status:
          type: string
          description: the current status of the feed connection
          example: REJECTED
          enum:
          - PENDING
          - REJECTED
      description: A feed connection that links a financial institution account to a bank account in a
        Xero organisation
      externalDocs:
        url: https://developer.xero.com/documentation/bank-feeds-api/feed-connections
    Statement:
      type: object
      properties:
        statementLines:
          description: Transaction lines of the statement
          allOf:
          - $ref: '#/components/schemas/StatementLines'
        endDate:
          type: string
          description: Closing balance date ISO-8601 YYYY-MM-DD
          format: date
          example: '2018-07-27'
        endBalance:
          description: Closing balance of the statement
          allOf:
          - $ref: '#/components/schemas/EndBalance'
        statementLineCount:
          type: integer
          description: Number of statement lines in the statement
          example: 1
        id:
          type: string
          description: GUID used to identify the Statement
          format: uuid
          example: ba4f3127-5e46-427d-80ea-dea2fcd26afe
        feedConnectionId:
          type: string
          description: The Xero generated feed connection Id that identifies the Xero Bank Account Container
            into which the statement should be delivered. This is obtained by calling GET FeedConnections
          format: uuid
          example: 87cb0dc8-fa32-409c-b622-19f8de8dcc83
        startDate:
          type: string
          description: Opening balance date (can be no older than one year from the current date) ISO-8601
            YYYY-MM-DD
          format: date
          example: '2018-07-27'
        startBalance:
          description: Opening balance of the statement
          allOf:
          - $ref: '#/components/schemas/StartBalance'
        errors:
          type: array
          description: Details of why the statement was rejected
          items:
            $ref: '#/components/schemas/Error'
        status:
          type: string
          description: Current status of statements
          example: PENDING
          enum:
          - PENDING
          - REJECTED
          - DELIVERED
      description: A bank statement delivered to a feed connection, with its opening and closing balances
        and statement lines
    EndBalance:
      type: object
      properties:
        amount:
          type: number
          description: decimal(19,4) unsigned closing balance amount
          format: double
          example: 10.134
          x-is-money: true
        creditDebitIndicator:
          description: Whether the closing balance is a credit or a debit, from the perspective of the
            customer
          allOf:
          - $ref: '#/components/schemas/CreditDebitIndicator'
      description: The StartBalance plus all the Statement Line Amounts should be equal to the EndBalance
        Amount
    Error:
      type: object
      properties:
        detail:
          maximum: 255
          type: string
          description: Human readable detailed error description
          example: The application has not been configured to use these API endpoints.
        title:
          maximum: 255
          type: string
          description: Human readable high level error description
          example: Invalid Application
        type:
          type: string
          description: Identifies the type of error
          example: invalid-application
          enum:
          - invalid-request
          - invalid-application
          - invalid-feed-connection
          - duplicate-statement
          - invalid-end-balance
          - invalid-start-and-end-date
          - invalid-start-date
          - internal-error
          - feed-already-connected-in-current-organisation
          - invalid-end-date
          - statement-not-found
          - feed-connected-in-different-organisation
          - feed-already-connected-in-different-organisation
          - bank-feed-not-found
          - invalid-country-specified
          - invalid-organisation-bank-feeds
          - invalid-organisation-multi-currency
          - invalid-feed-connection-for-organisation
          - invalid-user-role
          - account-not-valid
          - feed-not-found-or-already-deleted
        status:
          type: integer
          description: The numeric HTTP Status Code, e.g. 404
          example: 403
      description: On error, the API consumer will receive an HTTP response with a HTTP Status Code of
        4xx or 5xx and a Content-Type of application/problem+json
    StartBalance:
      type: object
      properties:
        amount:
          type: number
          description: decimal(19,4) unsigned Opening/closing balance amount
          format: double
          example: 9.0
          x-is-money: true
        creditDebitIndicator:
          description: Whether the opening balance is a credit or a debit, from the perspective of the
            customer
          allOf:
          - $ref: '#/components/schemas/CreditDebitIndicator'
      description: The starting balance of the statement
    CreditDebitIndicator:
      type: string
      description: If the statement balances are credit or debit, the CreditDebitIndicator should be specified
        from the perspective of the Customer
      enum:
      - CREDIT
      - DEBIT
    CurrencyCode:
      type: string
      description: 3 letter alpha code for the ISO-4217 currency code, e.g. USD, AUD
      example: AUD
      enum:
      - AED
      - AFN
      - ALL
      - AMD
      - ANG
      - AOA
      - ARS
      - AUD
      - AWG
      - AZN
      - BAM
      - BBD
      - BDT
      - BGN
      - BHD
      - BIF
      - BMD
      - BND
      - BOB
      - BRL
      - BSD
      - BTN
      - BWP
      - BYN
      - BZD
      - CAD
      - CDF
      - CHF
      - CLP
      - CNY
      - COP
      - CRC
      - CUC
      - CUP
      - CVE
      - CZK
      - DJF
      - DKK
      - DOP
      - DZD
      - EGP
      - ERN
      - ETB
      - EUR
      - FJD
      - FKP
      - GBP
      - GEL
      - GGP
      - GHS
      - GIP
      - GMD
      - GNF
      - GTQ
      - GYD
      - HKD
      - HNL
      - HRK
      - HTG
      - HUF
      - IDR
      - ILS
      - IMP
      - INR
      - IQD
      - IRR
      - ISK
      - JEP
      - JMD
      - JOD
      - JPY
      - KES
      - KGS
      - KHR
      - KMF
      - KPW
      - KRW
      - KWD
      - KYD
      - KZT
      - LAK
      - LBP
      - LKR
      - LRD
      - LSL
      - LYD
      - MAD
      - MDL
      - MGA
      - MKD
      - MMK
      - MNT
      - MOP
      - MRU
      - MUR
      - MVR
      - MWK
      - MXN
      - MYR
      - MZN
      - NAD
      - NGN
      - NIO
      - NOK
      - NPR
      - NZD
      - OMR
      - PAB
      - PEN
      - PGK
      - PHP
      - PKR
      - PLN
      - PYG
      - QAR
      - RON
      - RSD
      - RUB
      - RWF
      - SAR
      - SBD
      - SCR
      - SDG
      - SEK
      - SGD
      - SHP
      - SLL
      - SOS
      - SPL
      - SRD
      - STN
      - SVC
      - SYP
      - SZL
      - THB
      - TJS
      - TMT
      - TND
      - TOP
      - TRY
      - TTD
      - TVD
      - TWD
      - TZS
      - UAH
      - UGX
      - USD
      - UYU
      - UZS
      - VEF
      - VND
      - VUV
      - WST
      - XAF
      - XCD
      - XDR
      - XOF
      - XPF
      - YER
      - ZAR
      - ZMW
      - ZMK
      - ZWD
    Pagination:
      type: object
      properties:
        pageCount:
          type: integer
          description: Number of pages available
          example: 1
        pageSize:
          type: integer
          description: Page size which specifies how many records per page will be returned (default 50).
            Example - https://api.xero.com/bankfeeds.xro/1.0/Statements?pageSize=100 to specify page size
            of 100
          example: 10
        page:
          type: integer
          description: Page number which specifies the set of records to retrieve. Example - https://api.xero.com/bankfeeds.xro/1.0/Statements?page=2
            to get the second set of the records. When page value is not a number or a negative number,
            by default, the first set of records is returned
          example: 1
        itemCount:
          type: integer
          description: Number of items returned
          example: 2
      description: Pagination details of the returned page of results
    StatementLine:
      type: object
      properties:
        reference:
          maximum: 255
          type: string
          description: Optional field to enhance the Description
          example: Reference for statement line 2
        transactionType:
          maximum: 30
          type: string
          description: Descriptive transaction type
          example: Refund
        payeeName:
          maximum: 255
          type: string
          description: Typically the merchant or payee name
          example: Payee name for statement line 2
        amount:
          type: number
          description: Transaction amount
          format: double
          example: 5.0
          x-is-money: true
        description:
          maximum: 2000
          type: string
          description: Transaction description
          example: Description for statement line 2
        chequeNumber:
          maximum: 20
          type: string
          description: The cheque/check number
          example: '021'
        creditDebitIndicator:
          description: Whether the transaction is a credit or a debit, from the perspective of the customer
          allOf:
          - $ref: '#/components/schemas/CreditDebitIndicator'
        transactionId:
          type: string
          description: Financial institute's internal transaction identifier. If provided this field is
            factored into duplicate detection
          example: transaction-id-2
        postedDate:
          type: string
          description: The date that the transaction was processed or cleared as seen in internet banking
            ISO-8601 YYYY-MM-DD
          format: date
          example: '2018-06-10'
      description: the lines details for a statement
    Statements:
      type: object
      properties:
        pagination:
          description: Pagination details of the returned page of results
          allOf:
          - $ref: '#/components/schemas/Pagination'
        items:
          type: array
          description: List of statements
          items:
            $ref: '#/components/schemas/Statement'
      description: A page of statements, or the statements submitted in a create request
      externalDocs:
        url: https://developer.xero.com/documentation/bank-feeds-api/statements
    StatementLines:
      type: array
      description: The transaction lines of a statement
      items:
        $ref: '#/components/schemas/StatementLine'
    CountryCode:
      type: string
      description: ISO-3166 alpha-2 country code, e.g. US, AU This element is required only when the Application
        supports multi-region. Talk to your Partner Manager to confirm if this is the case
      example: GB
      enum:
      - AD
      - AE
      - AF
      - AG
      - AI
      - AL
      - AM
      - AN
      - AO
      - AQ
      - AR
      - AS
      - AT
      - AU
      - AW
      - AZ
      - BA
      - BB
      - BD
      - BE
      - BF
      - BG
      - BH
      - BI
      - BJ
      - BL
      - BM
      - BN
      - BO
      - BR
      - BS
      - BT
      - BW
      - BY
      - BZ
      - CA
      - CC
      - CD
      - CF
      - CG
      - CH
      - CI
      - CK
      - CL
      - CM
      - CN
      - CO
      - CR
      - CU
      - CV
      - CW
      - CX
      - CY
      - CZ
      - DE
      - DJ
      - DK
      - DM
      - DO
      - DZ
      - EC
      - EE
      - EG
      - EH
      - ER
      - ES
      - ET
      - FI
      - FJ
      - FK
      - FM
      - FO
      - FR
      - GA
      - GB
      - GD
      - GE
      - GG
      - GH
      - GI
      - GL
      - GM
      - GN
      - GQ
      - GR
      - GT
      - GU
      - GW
      - GY
      - HK
      - HN
      - HR
      - HT
      - HU
      - ID
      - IE
      - IL
      - IM
      - IN
      - IO
      - IQ
      - IR
      - IS
      - IT
      - JE
      - JM
      - JO
      - JP
      - KE
      - KG
      - KH
      - KI
      - KM
      - KN
      - KP
      - KR
      - KW
      - KY
      - KZ
      - LA
      - LB
      - LC
      - LI
      - LK
      - LR
      - LS
      - LT
      - LU
      - LV
      - LY
      - MA
      - MC
      - MD
      - ME
      - MF
      - MG
      - MH
      - MK
      - ML
      - MM
      - MN
      - MO
      - MP
      - MR
      - MS
      - MT
      - MU
      - MV
      - MW
      - MX
      - MY
      - MZ
      - NA
      - NC
      - NE
      - NG
      - NI
      - NL
      - 'NO'
      - NP
      - NR
      - NU
      - NZ
      - OM
      - PA
      - PE
      - PF
      - PG
      - PH
      - PK
      - PL
      - PM
      - PN
      - PR
      - PS
      - PT
      - PW
      - PY
      - QA
      - RE
      - RO
      - RS
      - RU
      - RW
      - SA
      - SB
      - SC
      - SD
      - SE
      - SG
      - SH
      - SI
      - SJ
      - SK
      - SL
      - SM
      - SN
      - SO
      - SR
      - SS
      - ST
      - SV
      - SX
      - SY
      - SZ
      - TC
      - TD
      - TG
      - TH
      - TJ
      - TK
      - TL
      - TM
      - TN
      - TO
      - TR
      - TT
      - TV
      - TW
      - TZ
      - UA
      - UG
      - US
      - UY
      - UZ
      - VA
      - VC
      - VE
      - VG
      - VI
      - VN
      - VU
      - WF
      - WS
      - XK
      - YE
      - YT
      - ZA
      - ZM
      - ZW
    FeedConnections:
      type: object
      properties:
        pagination:
          description: Pagination details of the returned page of results
          allOf:
          - $ref: '#/components/schemas/Pagination'
        items:
          type: array
          description: List of feed connections
          items:
            $ref: '#/components/schemas/FeedConnection'
      description: A page of feed connections, or the feed connections submitted in a create or delete
        request
      externalDocs:
        url: https://developer.xero.com/documentation/bank-feeds-api/feed-connections
  parameters:
    requiredHeader:
      name: Xero-Tenant-Id
      in: header
      description: Xero identifier for Tenant
      required: true
      style: simple
      explode: false
      schema:
        type: string
      x-ballerina-name: xeroTenantId
    idempotencyKey:
      name: Idempotency-Key
      in: header
      description: This allows you to safely retry requests without the risk of duplicate processing.
        128 character max
      required: false
      style: simple
      explode: false
      schema:
        type: string
      example: KEY_VALUE
      x-snake: idempotency_key
      x-ballerina-name: idempotencyKey
  securitySchemes:
    OAuth2:
      type: oauth2
      description: For more information visit https://developer.xero.com/documentation/oauth2/overview
      flows:
        authorizationCode:
          authorizationUrl: https://login.xero.com/identity/connect/authorize
          tokenUrl: https://identity.xero.com/connect/token
          scopes:
            email: Grant read-only access to your email
            openid: Grant read-only access to your open id
            profile: your profile information
            bankfeeds: Grant read-write access to bankfeeds
